# Import the current theme
include themes/current.conf

# General settings
clear_all_shortcuts     yes
confirm_os_window_close 0
placement_strategy      center
resize_in_steps         yes
window_padding_width    0

# Font settings
font_size        14
font_family      Recursive Mono Casual
bold_font        auto
italic_font      auto
bold_italic_font auto

# Keybindings
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+equal change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.o
