add_newline = false
format = """
 $directory$git_branch$git_status\
 $c$lua$nodejs$python$rust\
 $nix_shell$cmd_duration$status
 $character
"""

[directory]
read_only = ' 󰌾'
truncation_length = 7
format = '[$path]($style)[$read_only]($read_only_style) '

[git_branch]
symbol = '󰘬 '
format = 'on [$symbol$branch(:$remote_branch)]($style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[nix_shell]
symbol = '󱄅 '
format = '[$symbol$state]($style) '

[cmd_duration]
format = '[$duration]($style) '

[status]
format = '[$symbol$status]($style) '

[character]
format = '$symbol '

[c]
symbol = ' '
format = '[$symbol($version(-$name) )]($style)'

[lua]
symbol = '󰢱 '
format = '[$symbol($version )]($style)'

[nodejs]
symbol = '󰎙 '
format = '[$symbol($version )]($style)'

[python]
symbol = '󰌠 '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = '󱘗 '
format = '[$symbol($version )]($style)'
