local M = {}

-- stylua: ignore start

function M.get(spec)
  local pal, diag, diff = spec.palette, spec.diagnostics, spec.diff
  local editor = spec.editor
  return {
    ColorColumn          = { link = 'WinSeparator' },
    Conceal              = editor.conceal,
    CurSearch            = { link = 'IncSearch' },
    Cursor               = editor.cursor,
    lCursor              = { link = 'Cursor' },
    CursorIM             = { link = 'Cursor' },
    CursorColumn         = { link = 'CursorLine' },
    CursorLine           = editor.cursorline,
    Directory            = editor.directory,
    DiffAdd              = { bg = diff.add },
    DiffChange           = { bg = diff.change },
    DiffDelete           = { bg = diff.delete },
    DiffText             = { bg = diff.text },
    DiffTextAdd          = { link = 'DiffText' },
    EndOfBuffer          = { link = 'NonText' },
    TermCursor           = { link = 'Cursor' },
    OkMsg                = { fg = diag.ok },
    ErrorMsg             = { fg = diag.error, bold = true, underline = true },
    StderrMsg            = { link = 'ErrorMsg' },
    StdoutMsg            = {},
    WinSeparator         = editor.winsep,
    Folded               = editor.folded,
    FoldColumn           = editor.foldcol,
    SignColumn           = { fg = pal.fg },
    IncSearch            = editor.incsearch,
    Substitute           = editor.substitute,
    LineNr               = editor.linenr,
    LineNrAbove          = { link = 'LineNr' },
    LineNrBelow          = { link = 'LineNr' },
    CursorLineNr         = { fg = pal.fg },
    CursorLineFold       = { link = 'FoldColumn' },
    CursorLineSign       = { link = 'SignColumn' },
    MatchParen           = editor.matchparen,
    ModeMsg              = { fg = pal.fg, bold = true },
    MsgArea              = {},
    MsgSeparator         = { link = 'StatusLine' },
    MoreMsg              = { fg = pal.yellow, bold = true },
    NonText              = editor.nontext,
    Normal               = editor.normal,
    NormalFloat          = { link = 'Normal' },
    FloatBorder          = editor.border,
    FloatTitle           = { link = 'Title' },
    FloatFooter          = { link = 'Title' },
    NormalNC             = { link = 'Normal' },
    Pmenu                = editor.pmenu,
    PmenuSel             = editor.pmenusel,
    PmenuKind            = { link = 'Pmenu' },
    PmenuKindSel         = { link = 'PmenuSel' },
    PmenuExtra           = { link = 'Pmenu' },
    PmenuExtraSel        = { link = 'PmenuSel' },
    PmenuSbar            = { link = 'Pmenu' },
    PmenuThumb           = editor.pmenuthumb,
    PmenuMatch           = { bold = true },
    PmenuMatchSel        = { bold = true },
    ComplMatchIns        = {},
    ComplHint            = { link = 'NonText' },
    ComplHintMore        = { link = 'MoreMsg' },
    Question             = editor.question,
    QuickFixLine         = editor.quickfix,
    Search               = editor.search,
    SnippetTabstop       = { link = 'Visual' },
    SnippetTabstopActive = { link = 'SnippetTabStop' },
    SpecialKey           = editor.special,
    SpellBad             = { sp = diag.error, undercurl = true },
    SpellCap             = { sp = diag.info, undercurl = true },
    SpellLocal           = { sp = diag.ok, undercurl = true },
    SpellRare            = { sp = diag.hint, undercurl = true },
    StatusLine           = editor.statusline,
    StatusLineNC         = { link = 'StatusLine' },
    StatusLineTerm       = { link = 'StatusLine' },
    StatusLineTermNC     = { link = 'StatusLine' },
    TabLine              = editor.tabline,
    TabLineFill          = { link = 'TabLine' },
    TabLineSel           = { link = 'Normal' },
    Title                = editor.title,
    Visual               = { bg = pal.bgv },
    VisualNOS            = { link = 'Visual' },
    WarningMsg           = { fg = diag.warn, bold = true },
    Whitespace           = { link = 'NonText' },
    WildMenu             = { link = 'Search' },
    WinBar               = { fg = pal.grey1, bg = pal.bgd },
    WinBarNC             = { link = 'WinBar' },
  }
end

-- stylua: ignore end

return M
